# -*- coding: utf-8 -*-
"""Final Project

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1q14H67pDbI6_jTnGmBUQPbsx8ksXyfPH
"""

#Scrap data from "https://uca.edu"

from bs4 import BeautifulSoup
import requests
import pandas as pd

print("University of Central Arkansas")
print("https://uca.edu")

def pakistan_history():
 url="https://uca.edu/politicalscience/home/research-projects/dadm-project/asiapacific-region/pakistan-1947-present/"
 page=requests.get (url)

 Soup=BeautifulSoup(page.content,"html5")
 title=Soup.find(class_="wrap")
 print(title.text)

 entrytitle=Soup.find(class_="entry-title")
 print(entrytitle.text)

 Content=Soup.find(class_="entry-content")
 print(Content.text)
pakistan_history()

def india_history():
 url="https://uca.edu/politicalscience/home/research-projects/dadm-project/asiapacific-region/india-1947-present/"
 page=requests.get(url)

 Soup=BeautifulSoup(page.content,"html5")
 title=Soup.find(class_="entry-title")
 print(title.text)

 Content=Soup.find(class_="entry-content")
 print(Content.text)
india_history()

def afghanistan_history():
 url="https://uca.edu/politicalscience/home/research-projects/dadm-project/asiapacific-region/afghanistan-1919-present/"
 page=requests.get(url)

 Soup=BeautifulSoup(page.content,"html5")
 title=Soup.find(class_="entry-title")
 print(title.text)

 Content=Soup.find(class_="entry-content")
 print(Content.text)
afghanistan_history()

def iran_history():
 url="https://uca.edu/politicalscience/home/research-projects/dadm-project/middle-eastnorth-africapersian-gulf-region/iran-1905-present/"
 page=requests.get(url)

 Soup=BeautifulSoup(page.content,"html5")
 title=Soup.find(class_="entry-title")
 print(title.text)

 Content=Soup.find(class_="entry-content")
 print(Content.text)
iran_history()

def bangladesh_history():
 url="https://uca.edu/politicalscience/home/research-projects/dadm-project/asiapacific-region/bangladesh-1971-present/"
 page=requests.get(url)

 Soup=BeautifulSoup(page.content,"html5")
 title=Soup.find(class_="entry-title")
 print(title.text)

 Content=Soup.find(class_="entry-content")
 print(Content.text)
bangladesh_history()

def israel_palestine_history():
 url="https://uca.edu/politicalscience/home/research-projects/dadm-project/middle-eastnorth-africapersian-gulf-region/israelpalestine-1948-present/"
 page=requests.get(url)

 Soup=BeautifulSoup(page.content,"html5")
 title=Soup.find(class_="entry-title")
 print(title.text)

 Content=Soup.find(class_="entry-content")
 print(Content.text)
israel_palestine_history()

def lebanon_history():
 url="https://uca.edu/politicalscience/home/research-projects/dadm-project/middle-eastnorth-africapersian-gulf-region/lebanon-1943-present/"
 page=requests.get(url)

 Soup=BeautifulSoup(page.content,"html5")
 title=Soup.find(class_="entry-title")
 print(title.text)

 Content=Soup.find(class_="entry-content")
 print(Content.text)
lebanon_history()

def turkey_history():
  url="https://uca.edu/politicalscience/home/research-projects/dadm-project/middle-eastnorth-africapersian-gulf-region/republic-of-turkey-1923-present/"
  page=requests.get(url)

  soup=BeautifulSoup(page.content,"html5")
  title=soup.find(class_="entry-title")
  print(title.text)

  content=soup.find(class_="entry-content")
  print(content.text)
turkey_history()

def srilanka_history():
  url="https://uca.edu/politicalscience/home/research-projects/dadm-project/asiapacific-region/ceylonsri-lanka-1948-present/"
  page=requests.get(url)

  soup=BeautifulSoup(page.content,"html5")
  title=soup.find(class_="entry-title")
  print(title.text)

  content=soup.find(class_="entry-content")
  print(content.text)
srilanka_history()

def world_history():
  url="https://uca.edu/ubulletin2013/courses/history-hist/"
  page=requests.get(url)

  soup=BeautifulSoup(page.content,"html5")
  title=soup.find(class_="entry-title")
  print(title.text)

  content=soup.find(class_="entry-content")
  print(content.text)
world_history()

print("http://uca.edu/go/avid/")
print("Email: ","mailto:carnold@uca.edu")

#Converting code into CSV file.

all_data = []

def scrap_country_history(url, index):
    page = requests.get(url)
    soup = BeautifulSoup(page.content, "html5")
    title = soup.find(class_="entry-title").text
    content = soup.find(class_="entry-content").text
    all_data.append([index, title, content])
urls = [
    "https://uca.edu/politicalscience/home/research-projects/dadm-project/asiapacific-region/pakistan-1947-present/",
    "https://uca.edu/politicalscience/home/research-projects/dadm-project/asiapacific-region/india-1947-present/",
    "https://uca.edu/politicalscience/home/research-projects/dadm-project/asiapacific-region/afghanistan-1919-present/",
    "https://uca.edu/politicalscience/home/research-projects/dadm-project/middle-eastnorth-africapersian-gulf-region/iran-1905-present/",
    "https://uca.edu/politicalscience/home/research-projects/dadm-project/asiapacific-region/bangladesh-1971-present/",
    "https://uca.edu/politicalscience/home/research-projects/dadm-project/middle-eastnorth-africapersian-gulf-region/israelpalestine-1948-present/",
    "https://uca.edu/politicalscience/home/research-projects/dadm-project/middle-eastnorth-africapersian-gulf-region/lebanon-1943-present/",
    "https://uca.edu/politicalscience/home/research-projects/dadm-project/middle-eastnorth-africapersian-gulf-region/republic-of-turkey-1923-present/",
    "https://uca.edu/politicalscience/home/research-projects/dadm-project/asiapacific-region/ceylonsri-lanka-1948-present/",
    "https://uca.edu/ubulletin2013/courses/history-hist/"
]

for index, url in enumerate(urls, start=1):
    scrap_country_history(url, index)

df = pd.DataFrame(all_data, columns=["Index", "Title", "Content"])

df.to_csv("Final Project.csv",)

print("Data saved successfully.")